### ISSUE TITLE
bumpversion errors

### ISSUE THREAD

**Issue by dangillet** [pythonarcade/pyglet-ffmpeg#1]
Trying to use bumpversion, I ran in the following issue `TypeError: environment can only contain strings`.

I found the following issue in their issue tracker: https://github.com/peritus/bumpversion/issues/67

According to the last message, the development is rather inactive but there is another fork from this project  [bump2version](https://github.com/c4urself/bump2version).

Any chance to investigate if this could replace the actual bumpversion?

**Comment by pauleveritt** [comment]
You're right, that package is *dead*. Wow, four years.

I pushed a change that bumps the version of bumpversion (hehe).
